### PR TITLE
fix(build): COLLECTION_DEFINITION_FOLDER and VIEWS_DEFINITION_FOLDER to support both relative and absolute path

### PR DESCRIPTION
**Pull request by ThisIsDemetrio**
## Pull Request Type

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [X] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Description

This Pull Request fix a problem noted in #27 .

Add a quick function that build the path, based on the `isAbsolute` function. With this, the environment variables COLLECTION_DEFINITION_FOLDER and VIEWS_DEFINITION_FOLDER can be populated with each relative and absolute path, thus:
- making the `default.env` file becoming necessary to run the CRUD Service without further modifications;
- simplifying the process of generating your own environment variables;

Test has been included making sure that these variables works both ways.

## PR Checklist

- [X] The commit message follows our guidelines included in the [CONTRIBUTING.md](../CONTRIBUTING.md#how-to-submit-a-pr)
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by fredmaggiowski** [comment]
May I ask what is the use case for this? Generally you'd provide the file without knowledge of what is the cwd of the running node process so the absolute path is the way to go to be sure you don't miss the file location; why is needed to accept a relative path?  🤔

**Comment by danibix95** [comment]
> May I ask what is the use case for this? Generally you'd provide the file without knowledge of where the process is running in the file system (what cwd is being used by the node script) so the absolute path is the way to go to be sure you don't miss the file location; why is it needed to accept a relative path then? thinking

I think the change is related to simplifying local development

**Review by danibix95 — APPROVED** [review]
The changes look good. Let's discuss with @fredmaggiowski about the need to introduce them and then we can either merge or close it.  
Thank you for the modifications.

**Comment by fredmaggiowski** [comment]
> The changes look good. Let's discuss with @fredmaggiowski about the need to introduce them and then we can either merge or close it. Thank you for the modifications.

don't get me wrong, I don't want to block the PR, i was just curious since it seems odd to me to have this kind of configuration in production; couldn't local development being simplified without the need to change the code behaviour? 🤔

**Comment by ThisIsDemetrio** [comment]
> > The changes look good. Let's discuss with @fredmaggiowski about the need to introduce them and then we can either merge or close it. Thank you for the modifications.
> 
> don't get me wrong, I don't want to block the PR, i was just curious since it seems odd to me to have this kind of configuration in production; couldn't local development being simplified without the need to change the code behaviour? thinking

That's completely understandable. I guess it's difficult to see relative paths to the definitions files in production, but I never saw it as a bad practice, (but it's just better to avoid it because relative paths might be tricky to configure).But that's my point of view, and it could be wrong.

This PR is 100% intended to help run in local environments. Yet, it doesn't block the execution in local of the application (tho I'd add a couple of words in the readme to explain that paths must be updated).

**Comment by fredmaggiowski** [comment]
> > > The changes look good. Let's discuss with @fredmaggiowski about the need to introduce them and then we can either merge or close it. Thank you for the modifications.
>> 
>> don't get me wrong, I don't want to block the PR, i was just curious since it seems odd to me to have this kind of configuration in production; couldn't local development being simplified without the need to change the code behaviour? thinking

>That's completely understandable. I guess it's difficult to see relative paths to the definitions files in production, but I never saw it as a bad practice, (but it's just better to avoid it because relative paths might be tricky to configure).But that's my point of view, and it could be wrong.

>This PR is 100% intended to help run in local environments. Yet, it doesn't block the execution in local of the application (tho I'd add a couple of words in the readme to explain that paths must be updated).

What about changing the readme with a $PWD in the example so that the relative path a user might use is automatically expanded to absolute, this wouldn't require a change in the code 🤷

**Comment by ThisIsDemetrio** [comment]
> What about changing the readme with a $PWD in the example so that the relative path a user might use is automatically expanded to absolute, this wouldn't require a change in the code shrug

Probably the safest solution, since we don't touch the code, I like it.
So, I'm going to close this PR and propose a new one.

**Pull request closed without merging**
